
<?php
include 'config.core.php';
include MODX_CORE_PATH . 'model/modx/modx.class.php';
$modx = new modX();

$modx->setLogTarget(XPDO_CLI_MODE ? 'ECHO' : 'HTML');
$modx->initialize('mgr');

$modx->setLogLevel(modX::LOG_LEVEL_INFO);

//$modx->exec("UPDATE {$modx->getTableName('modResource')} SET uri = '' WHERE uri_override = 0");

$modx->call('modResource', 'refreshURIs', array(&$modx,401));
$modx->call('modResource', 'refreshURIs', array(&$modx,402));
$modx->call('modResource', 'refreshURIs', array(&$modx,403));
$modx->call('modResource', 'refreshURIs', array(&$modx,404));
$modx->call('modResource', 'refreshURIs', array(&$modx,314));
$modx->call('modResource', 'refreshURIs', array(&$modx,477));
$modx->call('modResource', 'refreshURIs', array(&$modx,361));
$modx->call('modResource', 'refreshURIs', array(&$modx,362));
$modx->call('modResource', 'refreshURIs', array(&$modx,363));
$modx->call('modResource', 'refreshURIs', array(&$modx,3));
$modx->call('modResource', 'refreshURIs', array(&$modx,473));
$modx->call('modResource', 'refreshURIs', array(&$modx,474));
$modx->call('modResource', 'refreshURIs', array(&$modx,475));
$modx->call('modResource', 'refreshURIs', array(&$modx,476));
$modx->call('modResource', 'refreshURIs', array(&$modx,351 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,352 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,353 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,355 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,356 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,357 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,358 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,359 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,360 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,5   ));
$modx->call('modResource', 'refreshURIs', array(&$modx,6   ));
$modx->call('modResource', 'refreshURIs', array(&$modx,340 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,342 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,343 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,344 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,345 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,346 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,347 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,348 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,349 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,10  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,22  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,24  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,364 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,38  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,39  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,300 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,301 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,302 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,303 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,41  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,42  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,45  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,82  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,308 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,309 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,46  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,304 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,305 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,306 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,307 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,49  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,64  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,65  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,296 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,297 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,365 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,350 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,71  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,316 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,317 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,318 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,319 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,320 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,321 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,322 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,323 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,324 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,325 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,326 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,288 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,289 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,290 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,291 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,292 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,293 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,294 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,295 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,299 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,83  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,84  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,88  ));
$modx->call('modResource', 'refreshURIs', array(&$modx,3152));
$modx->call('modResource', 'refreshURIs', array(&$modx,102 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,394 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,395 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,396 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,397 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,398 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,399 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,400 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,116 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,117 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,118 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,122 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,126 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,3256));
$modx->call('modResource', 'refreshURIs', array(&$modx,130 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,131 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,135 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,136 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,137 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,3868));
$modx->call('modResource', 'refreshURIs', array(&$modx,3869));
$modx->call('modResource', 'refreshURIs', array(&$modx,140 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,153 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,154 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,1994));
$modx->call('modResource', 'refreshURIs', array(&$modx,330 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,166 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,167 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,329 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,168 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,169 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,172 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,173 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,1995));
$modx->call('modResource', 'refreshURIs', array(&$modx,188 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,331 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,332 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,333 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,334 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,335 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,336 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,337 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,338 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,205 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,219 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,221 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,223 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,224 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,225 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,627 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,230 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,240 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,241 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,242 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,249 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,250 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,1532));
$modx->call('modResource', 'refreshURIs', array(&$modx,267 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,536 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,538 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,1411));
$modx->call('modResource', 'refreshURIs', array(&$modx,327 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,339 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,287 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,471 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,472 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,370 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,371 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,372 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,373 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,374 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,375 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,376 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,377 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,378 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,369 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,469 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,470 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,406 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,408 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,409 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,410 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,411 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,465 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,467 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,468 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,413 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,414 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,415 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,416 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,417 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,418 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,419 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,420 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,422 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,423 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,424 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,425 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,459 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,460 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,461 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,462 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,463 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,427 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,428 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,429 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,430 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,431 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,432 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,433 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,434 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,436 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,437 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,438 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,439 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,452 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,453 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,454 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,455 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,456 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,457 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,458 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,441 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,442 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,443 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,444 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,445 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,446 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,447 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,448 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,480 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,482 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,483 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,484 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,485 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,486 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,487 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,488 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,489 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,490 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,491 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,492 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,493 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,495 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,496 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,497 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,498 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,499 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,500 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,501 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,502 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,503 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,504 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,505 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,506 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,508 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,509 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,510 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,511 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,512 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,513 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,514 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,515 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,516 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,517 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,518 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,519 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,521 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,522 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,523 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,524 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,525 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,526 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,527 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,528 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,529 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,530 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,531 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,532 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,600 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,540 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,542 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,544 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,546 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,548 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,550 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,552 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,554 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,556 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,558 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,561 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,562 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,563 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,564 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,565 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,566 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,567 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,568 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,569 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,570 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,571 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,572 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,574 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,575 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,576 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,577 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,578 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,579 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,580 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,581 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,582 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,583 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,584 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,585 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,587 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,588 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,589 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,590 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,591 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,592 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,593 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,594 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,595 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,596 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,597 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,598 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,601 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,602 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,603 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,604 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,605 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,606 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,607 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,608 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,609 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,610 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,611 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,613 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,614 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,615 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,616 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,617 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,618 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,619 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,620 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,621 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,622 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,623 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,624 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,628 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,629 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,630 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,631 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,632 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,633 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,634 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,635 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,636 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,637 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,638 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,640 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,641 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,642 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,643 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,644 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,645 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,646 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,647 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,648 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,649 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,650 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,651 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,653 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,656 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,657 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,658 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,659 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,660 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,661 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,662 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,663 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,664 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,665 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,666 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,668 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,669 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,670 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,671 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,672 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,673 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,674 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,675 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,676 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,677 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,678 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,679 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,681 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,682 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,683 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,684 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,685 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,686 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,687 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,688 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,689 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,690 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,691 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,692 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,694 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,695 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,696 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,697 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,698 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,699 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,700 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,701 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,702 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,703 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,704 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,705 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,792 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,793 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,794 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,795 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,796 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,797 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,798 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,799 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,800 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,801 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,802 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,804 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,806 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,807 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,808 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,809 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,810 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,811 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,812 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,813 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,814 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,815 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,816 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,819 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,821 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,822 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,823 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,824 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,825 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,826 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,827 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,828 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,829 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,830 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,831 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,832 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,834 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,835 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,836 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,837 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,838 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,839 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,840 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,841 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,842 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,843 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,844 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,845 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,848 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,849 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,850 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,851 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,852 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,853 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,854 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,855 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,856 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,857 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,858 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,860 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,861 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,862 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,863 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,864 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,865 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,866 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,867 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,868 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,869 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,870 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,871 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,874 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,875 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,876 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,877 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,878 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,879 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,880 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,881 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,882 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,883 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,884 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,886 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,903 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,904 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,905 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,906 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,907 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,908 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,909 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,910 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,911 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,912 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,913 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,914 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,916 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,917 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,918 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,919 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,920 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,921 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,922 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,923 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,924 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,925 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,926 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,927 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,929 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,930 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,931 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,932 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,933 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,934 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,935 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,936 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,937 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,938 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,939 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,940 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,942 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,943 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,944 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,945 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,946 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,947 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,948 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,949 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,950 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,951 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,952 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,953 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,997 ));
$modx->call('modResource', 'refreshURIs', array(&$modx,1000));
$modx->call('modResource', 'refreshURIs', array(&$modx,1001));
$modx->call('modResource', 'refreshURIs', array(&$modx,1002));
$modx->call('modResource', 'refreshURIs', array(&$modx,1003));
$modx->call('modResource', 'refreshURIs', array(&$modx,1004));
$modx->call('modResource', 'refreshURIs', array(&$modx,1005));
$modx->call('modResource', 'refreshURIs', array(&$modx,1006));
$modx->call('modResource', 'refreshURIs', array(&$modx,1007));
$modx->call('modResource', 'refreshURIs', array(&$modx,1008));
$modx->call('modResource', 'refreshURIs', array(&$modx,1009));
$modx->call('modResource', 'refreshURIs', array(&$modx,1010));
$modx->call('modResource', 'refreshURIs', array(&$modx,1012));
$modx->call('modResource', 'refreshURIs', array(&$modx,1013));
$modx->call('modResource', 'refreshURIs', array(&$modx,1014));
$modx->call('modResource', 'refreshURIs', array(&$modx,1015));
$modx->call('modResource', 'refreshURIs', array(&$modx,1016));
$modx->call('modResource', 'refreshURIs', array(&$modx,1017));
$modx->call('modResource', 'refreshURIs', array(&$modx,1019));
$modx->call('modResource', 'refreshURIs', array(&$modx,1020));
$modx->call('modResource', 'refreshURIs', array(&$modx,1021));
$modx->call('modResource', 'refreshURIs', array(&$modx,1022));
$modx->call('modResource', 'refreshURIs', array(&$modx,1023));
$modx->call('modResource', 'refreshURIs', array(&$modx,1024));
$modx->call('modResource', 'refreshURIs', array(&$modx,1026));
$modx->call('modResource', 'refreshURIs', array(&$modx,1027));
$modx->call('modResource', 'refreshURIs', array(&$modx,1028));
$modx->call('modResource', 'refreshURIs', array(&$modx,1029));
$modx->call('modResource', 'refreshURIs', array(&$modx,1030));
$modx->call('modResource', 'refreshURIs', array(&$modx,1031));
$modx->call('modResource', 'refreshURIs', array(&$modx,1032));
$modx->call('modResource', 'refreshURIs', array(&$modx,1033));
$modx->call('modResource', 'refreshURIs', array(&$modx,1034));
$modx->call('modResource', 'refreshURIs', array(&$modx,1035));
$modx->call('modResource', 'refreshURIs', array(&$modx,1036));
$modx->call('modResource', 'refreshURIs', array(&$modx,1037));
$modx->call('modResource', 'refreshURIs', array(&$modx,1039));
$modx->call('modResource', 'refreshURIs', array(&$modx,1040));
$modx->call('modResource', 'refreshURIs', array(&$modx,1041));
$modx->call('modResource', 'refreshURIs', array(&$modx,1042));
$modx->call('modResource', 'refreshURIs', array(&$modx,1043));
$modx->call('modResource', 'refreshURIs', array(&$modx,1044));
$modx->call('modResource', 'refreshURIs', array(&$modx,1045));
$modx->call('modResource', 'refreshURIs', array(&$modx,1046));
$modx->call('modResource', 'refreshURIs', array(&$modx,1047));
$modx->call('modResource', 'refreshURIs', array(&$modx,1048));
$modx->call('modResource', 'refreshURIs', array(&$modx,1049));
$modx->call('modResource', 'refreshURIs', array(&$modx,1050));
$modx->call('modResource', 'refreshURIs', array(&$modx,1052));
$modx->call('modResource', 'refreshURIs', array(&$modx,1053));
$modx->call('modResource', 'refreshURIs', array(&$modx,1054));
$modx->call('modResource', 'refreshURIs', array(&$modx,1055));
$modx->call('modResource', 'refreshURIs', array(&$modx,1056));
$modx->call('modResource', 'refreshURIs', array(&$modx,1057));
$modx->call('modResource', 'refreshURIs', array(&$modx,1058));
$modx->call('modResource', 'refreshURIs', array(&$modx,1059));
$modx->call('modResource', 'refreshURIs', array(&$modx,1060));
$modx->call('modResource', 'refreshURIs', array(&$modx,1061));
$modx->call('modResource', 'refreshURIs', array(&$modx,1062));
$modx->call('modResource', 'refreshURIs', array(&$modx,1063));
$modx->call('modResource', 'refreshURIs', array(&$modx,1065));
$modx->call('modResource', 'refreshURIs', array(&$modx,1066));
$modx->call('modResource', 'refreshURIs', array(&$modx,1067));
$modx->call('modResource', 'refreshURIs', array(&$modx,1068));
$modx->call('modResource', 'refreshURIs', array(&$modx,1069));
$modx->call('modResource', 'refreshURIs', array(&$modx,1070));
$modx->call('modResource', 'refreshURIs', array(&$modx,1071));
$modx->call('modResource', 'refreshURIs', array(&$modx,1072));
$modx->call('modResource', 'refreshURIs', array(&$modx,1073));
$modx->call('modResource', 'refreshURIs', array(&$modx,1074));
$modx->call('modResource', 'refreshURIs', array(&$modx,1075));
$modx->call('modResource', 'refreshURIs', array(&$modx,1076));
$modx->call('modResource', 'refreshURIs', array(&$modx,1079));
$modx->call('modResource', 'refreshURIs', array(&$modx,1082));
$modx->call('modResource', 'refreshURIs', array(&$modx,1083));
$modx->call('modResource', 'refreshURIs', array(&$modx,1084));
$modx->call('modResource', 'refreshURIs', array(&$modx,1085));
$modx->call('modResource', 'refreshURIs', array(&$modx,1086));
$modx->call('modResource', 'refreshURIs', array(&$modx,1087));
$modx->call('modResource', 'refreshURIs', array(&$modx,1088));
$modx->call('modResource', 'refreshURIs', array(&$modx,1089));
$modx->call('modResource', 'refreshURIs', array(&$modx,1090));
$modx->call('modResource', 'refreshURIs', array(&$modx,1091));
$modx->call('modResource', 'refreshURIs', array(&$modx,1092));
$modx->call('modResource', 'refreshURIs', array(&$modx,1094));
$modx->call('modResource', 'refreshURIs', array(&$modx,1095));
$modx->call('modResource', 'refreshURIs', array(&$modx,1096));
$modx->call('modResource', 'refreshURIs', array(&$modx,1097));
$modx->call('modResource', 'refreshURIs', array(&$modx,1098));
$modx->call('modResource', 'refreshURIs', array(&$modx,1099));
$modx->call('modResource', 'refreshURIs', array(&$modx,1101));
$modx->call('modResource', 'refreshURIs', array(&$modx,1102));
$modx->call('modResource', 'refreshURIs', array(&$modx,1103));
$modx->call('modResource', 'refreshURIs', array(&$modx,1104));
$modx->call('modResource', 'refreshURIs', array(&$modx,1105));
$modx->call('modResource', 'refreshURIs', array(&$modx,1106));
$modx->call('modResource', 'refreshURIs', array(&$modx,1108));
$modx->call('modResource', 'refreshURIs', array(&$modx,1109));
$modx->call('modResource', 'refreshURIs', array(&$modx,1110));
$modx->call('modResource', 'refreshURIs', array(&$modx,1111));
$modx->call('modResource', 'refreshURIs', array(&$modx,1112));
$modx->call('modResource', 'refreshURIs', array(&$modx,1113));
$modx->call('modResource', 'refreshURIs', array(&$modx,1114));
$modx->call('modResource', 'refreshURIs', array(&$modx,1115));
$modx->call('modResource', 'refreshURIs', array(&$modx,1116));
$modx->call('modResource', 'refreshURIs', array(&$modx,1117));
$modx->call('modResource', 'refreshURIs', array(&$modx,1118));
$modx->call('modResource', 'refreshURIs', array(&$modx,1119));
$modx->call('modResource', 'refreshURIs', array(&$modx,1121));
$modx->call('modResource', 'refreshURIs', array(&$modx,1122));
$modx->call('modResource', 'refreshURIs', array(&$modx,1123));
$modx->call('modResource', 'refreshURIs', array(&$modx,1124));
$modx->call('modResource', 'refreshURIs', array(&$modx,1125));
$modx->call('modResource', 'refreshURIs', array(&$modx,1126));
$modx->call('modResource', 'refreshURIs', array(&$modx,1127));
$modx->call('modResource', 'refreshURIs', array(&$modx,1128));
$modx->call('modResource', 'refreshURIs', array(&$modx,1129));
$modx->call('modResource', 'refreshURIs', array(&$modx,1130));
$modx->call('modResource', 'refreshURIs', array(&$modx,1131));
$modx->call('modResource', 'refreshURIs', array(&$modx,1132));
$modx->call('modResource', 'refreshURIs', array(&$modx,1134));
$modx->call('modResource', 'refreshURIs', array(&$modx,1135));
$modx->call('modResource', 'refreshURIs', array(&$modx,1136));
$modx->call('modResource', 'refreshURIs', array(&$modx,1137));
$modx->call('modResource', 'refreshURIs', array(&$modx,1138));
$modx->call('modResource', 'refreshURIs', array(&$modx,1139));
$modx->call('modResource', 'refreshURIs', array(&$modx,1140));
$modx->call('modResource', 'refreshURIs', array(&$modx,1141));
$modx->call('modResource', 'refreshURIs', array(&$modx,1142));
$modx->call('modResource', 'refreshURIs', array(&$modx,1143));
$modx->call('modResource', 'refreshURIs', array(&$modx,1144));
$modx->call('modResource', 'refreshURIs', array(&$modx,1145));
$modx->call('modResource', 'refreshURIs', array(&$modx,1147));
$modx->call('modResource', 'refreshURIs', array(&$modx,1148));
$modx->call('modResource', 'refreshURIs', array(&$modx,1149));
$modx->call('modResource', 'refreshURIs', array(&$modx,1150));
$modx->call('modResource', 'refreshURIs', array(&$modx,1151));
$modx->call('modResource', 'refreshURIs', array(&$modx,1152));
$modx->call('modResource', 'refreshURIs', array(&$modx,1153));
$modx->call('modResource', 'refreshURIs', array(&$modx,1154));
$modx->call('modResource', 'refreshURIs', array(&$modx,1155));
$modx->call('modResource', 'refreshURIs', array(&$modx,1156));
$modx->call('modResource', 'refreshURIs', array(&$modx,1157));
$modx->call('modResource', 'refreshURIs', array(&$modx,1158));
$modx->call('modResource', 'refreshURIs', array(&$modx,1163));
$modx->call('modResource', 'refreshURIs', array(&$modx,1166));
$modx->call('modResource', 'refreshURIs', array(&$modx,1167));
$modx->call('modResource', 'refreshURIs', array(&$modx,1168));
$modx->call('modResource', 'refreshURIs', array(&$modx,1169));
$modx->call('modResource', 'refreshURIs', array(&$modx,1170));
$modx->call('modResource', 'refreshURIs', array(&$modx,1171));
$modx->call('modResource', 'refreshURIs', array(&$modx,1172));
$modx->call('modResource', 'refreshURIs', array(&$modx,1173));
$modx->call('modResource', 'refreshURIs', array(&$modx,1174));
$modx->call('modResource', 'refreshURIs', array(&$modx,1175));
$modx->call('modResource', 'refreshURIs', array(&$modx,1176));
$modx->call('modResource', 'refreshURIs', array(&$modx,1178));
$modx->call('modResource', 'refreshURIs', array(&$modx,1179));
$modx->call('modResource', 'refreshURIs', array(&$modx,1180));
$modx->call('modResource', 'refreshURIs', array(&$modx,1181));
$modx->call('modResource', 'refreshURIs', array(&$modx,1182));
$modx->call('modResource', 'refreshURIs', array(&$modx,1183));
$modx->call('modResource', 'refreshURIs', array(&$modx,1245));
$modx->call('modResource', 'refreshURIs', array(&$modx,1185));
$modx->call('modResource', 'refreshURIs', array(&$modx,1186));
$modx->call('modResource', 'refreshURIs', array(&$modx,1187));
$modx->call('modResource', 'refreshURIs', array(&$modx,1188));
$modx->call('modResource', 'refreshURIs', array(&$modx,1189));
$modx->call('modResource', 'refreshURIs', array(&$modx,1190));
$modx->call('modResource', 'refreshURIs', array(&$modx,1192));
$modx->call('modResource', 'refreshURIs', array(&$modx,1193));
$modx->call('modResource', 'refreshURIs', array(&$modx,1194));
$modx->call('modResource', 'refreshURIs', array(&$modx,1195));
$modx->call('modResource', 'refreshURIs', array(&$modx,1196));
$modx->call('modResource', 'refreshURIs', array(&$modx,1197));
$modx->call('modResource', 'refreshURIs', array(&$modx,1198));
$modx->call('modResource', 'refreshURIs', array(&$modx,1199));
$modx->call('modResource', 'refreshURIs', array(&$modx,1200));
$modx->call('modResource', 'refreshURIs', array(&$modx,1201));
$modx->call('modResource', 'refreshURIs', array(&$modx,1202));
$modx->call('modResource', 'refreshURIs', array(&$modx,1203));
$modx->call('modResource', 'refreshURIs', array(&$modx,1205));
$modx->call('modResource', 'refreshURIs', array(&$modx,1206));
$modx->call('modResource', 'refreshURIs', array(&$modx,1207));
$modx->call('modResource', 'refreshURIs', array(&$modx,1208));
$modx->call('modResource', 'refreshURIs', array(&$modx,1209));
$modx->call('modResource', 'refreshURIs', array(&$modx,1210));
$modx->call('modResource', 'refreshURIs', array(&$modx,1211));
$modx->call('modResource', 'refreshURIs', array(&$modx,1212));
$modx->call('modResource', 'refreshURIs', array(&$modx,1213));
$modx->call('modResource', 'refreshURIs', array(&$modx,1214));
$modx->call('modResource', 'refreshURIs', array(&$modx,1215));
$modx->call('modResource', 'refreshURIs', array(&$modx,1216));
$modx->call('modResource', 'refreshURIs', array(&$modx,1218));
$modx->call('modResource', 'refreshURIs', array(&$modx,1219));
$modx->call('modResource', 'refreshURIs', array(&$modx,1220));
$modx->call('modResource', 'refreshURIs', array(&$modx,1221));
$modx->call('modResource', 'refreshURIs', array(&$modx,1222));
$modx->call('modResource', 'refreshURIs', array(&$modx,1223));
$modx->call('modResource', 'refreshURIs', array(&$modx,1224));
$modx->call('modResource', 'refreshURIs', array(&$modx,1225));
$modx->call('modResource', 'refreshURIs', array(&$modx,1226));
$modx->call('modResource', 'refreshURIs', array(&$modx,1227));
$modx->call('modResource', 'refreshURIs', array(&$modx,1228));
$modx->call('modResource', 'refreshURIs', array(&$modx,1229));
$modx->call('modResource', 'refreshURIs', array(&$modx,1231));
$modx->call('modResource', 'refreshURIs', array(&$modx,1232));
$modx->call('modResource', 'refreshURIs', array(&$modx,1233));
$modx->call('modResource', 'refreshURIs', array(&$modx,1234));
$modx->call('modResource', 'refreshURIs', array(&$modx,1235));
$modx->call('modResource', 'refreshURIs', array(&$modx,1236));
$modx->call('modResource', 'refreshURIs', array(&$modx,1237));
$modx->call('modResource', 'refreshURIs', array(&$modx,1238));
$modx->call('modResource', 'refreshURIs', array(&$modx,1239));
$modx->call('modResource', 'refreshURIs', array(&$modx,1240));
$modx->call('modResource', 'refreshURIs', array(&$modx,1241));
$modx->call('modResource', 'refreshURIs', array(&$modx,1242));
$modx->call('modResource', 'refreshURIs', array(&$modx,1248));
$modx->call('modResource', 'refreshURIs', array(&$modx,1249));
$modx->call('modResource', 'refreshURIs', array(&$modx,1250));
$modx->call('modResource', 'refreshURIs', array(&$modx,1251));
$modx->call('modResource', 'refreshURIs', array(&$modx,1252));
$modx->call('modResource', 'refreshURIs', array(&$modx,1253));
$modx->call('modResource', 'refreshURIs', array(&$modx,1254));
$modx->call('modResource', 'refreshURIs', array(&$modx,1255));
$modx->call('modResource', 'refreshURIs', array(&$modx,1256));
$modx->call('modResource', 'refreshURIs', array(&$modx,1257));
$modx->call('modResource', 'refreshURIs', array(&$modx,1258));
$modx->call('modResource', 'refreshURIs', array(&$modx,1260));
$modx->call('modResource', 'refreshURIs', array(&$modx,1261));
$modx->call('modResource', 'refreshURIs', array(&$modx,1262));
$modx->call('modResource', 'refreshURIs', array(&$modx,1263));
$modx->call('modResource', 'refreshURIs', array(&$modx,1264));
$modx->call('modResource', 'refreshURIs', array(&$modx,1265));
$modx->call('modResource', 'refreshURIs', array(&$modx,1267));
$modx->call('modResource', 'refreshURIs', array(&$modx,1268));
$modx->call('modResource', 'refreshURIs', array(&$modx,1269));
$modx->call('modResource', 'refreshURIs', array(&$modx,1270));
$modx->call('modResource', 'refreshURIs', array(&$modx,1271));
$modx->call('modResource', 'refreshURIs', array(&$modx,1272));
$modx->call('modResource', 'refreshURIs', array(&$modx,1274));
$modx->call('modResource', 'refreshURIs', array(&$modx,1275));
$modx->call('modResource', 'refreshURIs', array(&$modx,1276));
$modx->call('modResource', 'refreshURIs', array(&$modx,1277));
$modx->call('modResource', 'refreshURIs', array(&$modx,1278));
$modx->call('modResource', 'refreshURIs', array(&$modx,1279));
$modx->call('modResource', 'refreshURIs', array(&$modx,1280));
$modx->call('modResource', 'refreshURIs', array(&$modx,1281));
$modx->call('modResource', 'refreshURIs', array(&$modx,1282));
$modx->call('modResource', 'refreshURIs', array(&$modx,1283));
$modx->call('modResource', 'refreshURIs', array(&$modx,1284));
$modx->call('modResource', 'refreshURIs', array(&$modx,1285));
$modx->call('modResource', 'refreshURIs', array(&$modx,1287));
$modx->call('modResource', 'refreshURIs', array(&$modx,1288));
$modx->call('modResource', 'refreshURIs', array(&$modx,1289));
$modx->call('modResource', 'refreshURIs', array(&$modx,1290));
$modx->call('modResource', 'refreshURIs', array(&$modx,1291));
$modx->call('modResource', 'refreshURIs', array(&$modx,1292));
$modx->call('modResource', 'refreshURIs', array(&$modx,1293));
$modx->call('modResource', 'refreshURIs', array(&$modx,1294));
$modx->call('modResource', 'refreshURIs', array(&$modx,1295));
$modx->call('modResource', 'refreshURIs', array(&$modx,1296));
$modx->call('modResource', 'refreshURIs', array(&$modx,1297));
$modx->call('modResource', 'refreshURIs', array(&$modx,1298));
$modx->call('modResource', 'refreshURIs', array(&$modx,1300));
$modx->call('modResource', 'refreshURIs', array(&$modx,1301));
$modx->call('modResource', 'refreshURIs', array(&$modx,1302));
$modx->call('modResource', 'refreshURIs', array(&$modx,1303));
$modx->call('modResource', 'refreshURIs', array(&$modx,1304));
$modx->call('modResource', 'refreshURIs', array(&$modx,1305));
$modx->call('modResource', 'refreshURIs', array(&$modx,1306));
$modx->call('modResource', 'refreshURIs', array(&$modx,1307));
$modx->call('modResource', 'refreshURIs', array(&$modx,1308));
$modx->call('modResource', 'refreshURIs', array(&$modx,1309));
$modx->call('modResource', 'refreshURIs', array(&$modx,1310));
$modx->call('modResource', 'refreshURIs', array(&$modx,1311));
$modx->call('modResource', 'refreshURIs', array(&$modx,1313));
$modx->call('modResource', 'refreshURIs', array(&$modx,1314));
$modx->call('modResource', 'refreshURIs', array(&$modx,1315));
$modx->call('modResource', 'refreshURIs', array(&$modx,1316));
$modx->call('modResource', 'refreshURIs', array(&$modx,1317));
$modx->call('modResource', 'refreshURIs', array(&$modx,1318));
$modx->call('modResource', 'refreshURIs', array(&$modx,1319));
$modx->call('modResource', 'refreshURIs', array(&$modx,1320));
$modx->call('modResource', 'refreshURIs', array(&$modx,1321));
$modx->call('modResource', 'refreshURIs', array(&$modx,1322));
$modx->call('modResource', 'refreshURIs', array(&$modx,1323));
$modx->call('modResource', 'refreshURIs', array(&$modx,1324));
$modx->call('modResource', 'refreshURIs', array(&$modx,1327));
$modx->call('modResource', 'refreshURIs', array(&$modx,1560));
$modx->call('modResource', 'refreshURIs', array(&$modx,1563));
$modx->call('modResource', 'refreshURIs', array(&$modx,1330));
$modx->call('modResource', 'refreshURIs', array(&$modx,1331));
$modx->call('modResource', 'refreshURIs', array(&$modx,1332));
$modx->call('modResource', 'refreshURIs', array(&$modx,1333));
$modx->call('modResource', 'refreshURIs', array(&$modx,1334));
$modx->call('modResource', 'refreshURIs', array(&$modx,1335));
$modx->call('modResource', 'refreshURIs', array(&$modx,1336));
$modx->call('modResource', 'refreshURIs', array(&$modx,1337));
$modx->call('modResource', 'refreshURIs', array(&$modx,1338));
$modx->call('modResource', 'refreshURIs', array(&$modx,1339));
$modx->call('modResource', 'refreshURIs', array(&$modx,1340));
$modx->call('modResource', 'refreshURIs', array(&$modx,1342));
$modx->call('modResource', 'refreshURIs', array(&$modx,1343));
$modx->call('modResource', 'refreshURIs', array(&$modx,1344));
$modx->call('modResource', 'refreshURIs', array(&$modx,1345));
$modx->call('modResource', 'refreshURIs', array(&$modx,1346));
$modx->call('modResource', 'refreshURIs', array(&$modx,1347));
$modx->call('modResource', 'refreshURIs', array(&$modx,1349));
$modx->call('modResource', 'refreshURIs', array(&$modx,1350));
$modx->call('modResource', 'refreshURIs', array(&$modx,1351));
$modx->call('modResource', 'refreshURIs', array(&$modx,1352));
$modx->call('modResource', 'refreshURIs', array(&$modx,1353));
$modx->call('modResource', 'refreshURIs', array(&$modx,1354));
$modx->call('modResource', 'refreshURIs', array(&$modx,1356));
$modx->call('modResource', 'refreshURIs', array(&$modx,1357));
$modx->call('modResource', 'refreshURIs', array(&$modx,1358));
$modx->call('modResource', 'refreshURIs', array(&$modx,1359));
$modx->call('modResource', 'refreshURIs', array(&$modx,1360));
$modx->call('modResource', 'refreshURIs', array(&$modx,1361));
$modx->call('modResource', 'refreshURIs', array(&$modx,1362));
$modx->call('modResource', 'refreshURIs', array(&$modx,1363));
$modx->call('modResource', 'refreshURIs', array(&$modx,1364));
$modx->call('modResource', 'refreshURIs', array(&$modx,1365));
$modx->call('modResource', 'refreshURIs', array(&$modx,1366));
$modx->call('modResource', 'refreshURIs', array(&$modx,1367));
$modx->call('modResource', 'refreshURIs', array(&$modx,1369));
$modx->call('modResource', 'refreshURIs', array(&$modx,1370));
$modx->call('modResource', 'refreshURIs', array(&$modx,1371));
$modx->call('modResource', 'refreshURIs', array(&$modx,1372));
$modx->call('modResource', 'refreshURIs', array(&$modx,1373));
$modx->call('modResource', 'refreshURIs', array(&$modx,1374));
$modx->call('modResource', 'refreshURIs', array(&$modx,1375));
$modx->call('modResource', 'refreshURIs', array(&$modx,1376));
$modx->call('modResource', 'refreshURIs', array(&$modx,1377));
$modx->call('modResource', 'refreshURIs', array(&$modx,1378));
$modx->call('modResource', 'refreshURIs', array(&$modx,1379));
$modx->call('modResource', 'refreshURIs', array(&$modx,1380));
$modx->call('modResource', 'refreshURIs', array(&$modx,1382));
$modx->call('modResource', 'refreshURIs', array(&$modx,1383));
$modx->call('modResource', 'refreshURIs', array(&$modx,1384));
$modx->call('modResource', 'refreshURIs', array(&$modx,1385));
$modx->call('modResource', 'refreshURIs', array(&$modx,1386));
$modx->call('modResource', 'refreshURIs', array(&$modx,1387));
$modx->call('modResource', 'refreshURIs', array(&$modx,1388));
$modx->call('modResource', 'refreshURIs', array(&$modx,1389));
$modx->call('modResource', 'refreshURIs', array(&$modx,1390));
$modx->call('modResource', 'refreshURIs', array(&$modx,1391));
$modx->call('modResource', 'refreshURIs', array(&$modx,1392));
$modx->call('modResource', 'refreshURIs', array(&$modx,1393));
$modx->call('modResource', 'refreshURIs', array(&$modx,1395));
$modx->call('modResource', 'refreshURIs', array(&$modx,1396));
$modx->call('modResource', 'refreshURIs', array(&$modx,1397));
$modx->call('modResource', 'refreshURIs', array(&$modx,1398));
$modx->call('modResource', 'refreshURIs', array(&$modx,1399));
$modx->call('modResource', 'refreshURIs', array(&$modx,1400));
$modx->call('modResource', 'refreshURIs', array(&$modx,1401));
$modx->call('modResource', 'refreshURIs', array(&$modx,1402));
$modx->call('modResource', 'refreshURIs', array(&$modx,1403));
$modx->call('modResource', 'refreshURIs', array(&$modx,1404));
$modx->call('modResource', 'refreshURIs', array(&$modx,1405));
$modx->call('modResource', 'refreshURIs', array(&$modx,1406));
$modx->call('modResource', 'refreshURIs', array(&$modx,1559));
$modx->call('modResource', 'refreshURIs', array(&$modx,1413));
$modx->call('modResource', 'refreshURIs', array(&$modx,1421));
$modx->call('modResource', 'refreshURIs', array(&$modx,3455));
$modx->call('modResource', 'refreshURIs', array(&$modx,1424));
$modx->call('modResource', 'refreshURIs', array(&$modx,2750));
$modx->call('modResource', 'refreshURIs', array(&$modx,1552));
$modx->call('modResource', 'refreshURIs', array(&$modx,1720));
$modx->call('modResource', 'refreshURIs', array(&$modx,1729));
$modx->call('modResource', 'refreshURIs', array(&$modx,2184));
$modx->call('modResource', 'refreshURIs', array(&$modx,2146));
$modx->call('modResource', 'refreshURIs', array(&$modx,1835));
$modx->call('modResource', 'refreshURIs', array(&$modx,1844));
$modx->call('modResource', 'refreshURIs', array(&$modx,2222));
$modx->call('modResource', 'refreshURIs', array(&$modx,1986));
$modx->call('modResource', 'refreshURIs', array(&$modx,2000));
$modx->call('modResource', 'refreshURIs', array(&$modx,2044));
$modx->call('modResource', 'refreshURIs', array(&$modx,2045));
$modx->call('modResource', 'refreshURIs', array(&$modx,2072));
$modx->call('modResource', 'refreshURIs', array(&$modx,2074));
$modx->call('modResource', 'refreshURIs', array(&$modx,2068));
$modx->call('modResource', 'refreshURIs', array(&$modx,2371));
$modx->call('modResource', 'refreshURIs', array(&$modx,2451));
$modx->call('modResource', 'refreshURIs', array(&$modx,3864));
$modx->call('modResource', 'refreshURIs', array(&$modx,3870));
$modx->call('modResource', 'refreshURIs', array(&$modx,2433));
$modx->call('modResource', 'refreshURIs', array(&$modx,2584));
$modx->call('modResource', 'refreshURIs', array(&$modx,2530));
$modx->call('modResource', 'refreshURIs', array(&$modx,3867));
$modx->call('modResource', 'refreshURIs', array(&$modx,2751));
$modx->call('modResource', 'refreshURIs', array(&$modx,2758));
$modx->call('modResource', 'refreshURIs', array(&$modx,2726));
$modx->call('modResource', 'refreshURIs', array(&$modx,2698));
$modx->call('modResource', 'refreshURIs', array(&$modx,3681));
$modx->call('modResource', 'refreshURIs', array(&$modx,2714));
$modx->call('modResource', 'refreshURIs', array(&$modx,3390));
$modx->call('modResource', 'refreshURIs', array(&$modx,2735));
$modx->call('modResource', 'refreshURIs', array(&$modx,3875));
$modx->call('modResource', 'refreshURIs', array(&$modx,3005));
$modx->call('modResource', 'refreshURIs', array(&$modx,3754));
$modx->call('modResource', 'refreshURIs', array(&$modx,2841));
$modx->call('modResource', 'refreshURIs', array(&$modx,2982));
$modx->call('modResource', 'refreshURIs', array(&$modx,3623));
$modx->call('modResource', 'refreshURIs', array(&$modx,3625));
$modx->call('modResource', 'refreshURIs', array(&$modx,3101));
$modx->call('modResource', 'refreshURIs', array(&$modx,3102));
$modx->call('modResource', 'refreshURIs', array(&$modx,3116));
$modx->call('modResource', 'refreshURIs', array(&$modx,3117));
$modx->call('modResource', 'refreshURIs', array(&$modx,3125));
$modx->call('modResource', 'refreshURIs', array(&$modx,3132));
$modx->call('modResource', 'refreshURIs', array(&$modx,3146));
$modx->call('modResource', 'refreshURIs', array(&$modx,3159));
$modx->call('modResource', 'refreshURIs', array(&$modx,3160));
$modx->call('modResource', 'refreshURIs', array(&$modx,3161));
$modx->call('modResource', 'refreshURIs', array(&$modx,3162));
$modx->call('modResource', 'refreshURIs', array(&$modx,3163));
$modx->call('modResource', 'refreshURIs', array(&$modx,3164));
$modx->call('modResource', 'refreshURIs', array(&$modx,3165));
$modx->call('modResource', 'refreshURIs', array(&$modx,3166));
$modx->call('modResource', 'refreshURIs', array(&$modx,3167));
$modx->call('modResource', 'refreshURIs', array(&$modx,3168));
$modx->call('modResource', 'refreshURIs', array(&$modx,3169));
$modx->call('modResource', 'refreshURIs', array(&$modx,3170));
$modx->call('modResource', 'refreshURIs', array(&$modx,3172));
$modx->call('modResource', 'refreshURIs', array(&$modx,3173));
$modx->call('modResource', 'refreshURIs', array(&$modx,3174));
$modx->call('modResource', 'refreshURIs', array(&$modx,3175));
$modx->call('modResource', 'refreshURIs', array(&$modx,3176));
$modx->call('modResource', 'refreshURIs', array(&$modx,3177));
$modx->call('modResource', 'refreshURIs', array(&$modx,3178));
$modx->call('modResource', 'refreshURIs', array(&$modx,3179));
$modx->call('modResource', 'refreshURIs', array(&$modx,3180));
$modx->call('modResource', 'refreshURIs', array(&$modx,3181));
$modx->call('modResource', 'refreshURIs', array(&$modx,3182));
$modx->call('modResource', 'refreshURIs', array(&$modx,3183));
$modx->call('modResource', 'refreshURIs', array(&$modx,3184));
$modx->call('modResource', 'refreshURIs', array(&$modx,3185));
$modx->call('modResource', 'refreshURIs', array(&$modx,3186));
$modx->call('modResource', 'refreshURIs', array(&$modx,3187));
$modx->call('modResource', 'refreshURIs', array(&$modx,3188));
$modx->call('modResource', 'refreshURIs', array(&$modx,3189));
$modx->call('modResource', 'refreshURIs', array(&$modx,3190));
$modx->call('modResource', 'refreshURIs', array(&$modx,3191));
$modx->call('modResource', 'refreshURIs', array(&$modx,3192));
$modx->call('modResource', 'refreshURIs', array(&$modx,3193));
$modx->call('modResource', 'refreshURIs', array(&$modx,3194));
$modx->call('modResource', 'refreshURIs', array(&$modx,3195));
$modx->call('modResource', 'refreshURIs', array(&$modx,3196));
$modx->call('modResource', 'refreshURIs', array(&$modx,3865));
$modx->call('modResource', 'refreshURIs', array(&$modx,3601));
$modx->call('modResource', 'refreshURIs', array(&$modx,3247));
$modx->call('modResource', 'refreshURIs', array(&$modx,3252));
$modx->call('modResource', 'refreshURIs', array(&$modx,3255));
$modx->call('modResource', 'refreshURIs', array(&$modx,3259));
$modx->call('modResource', 'refreshURIs', array(&$modx,3264));
$modx->call('modResource', 'refreshURIs', array(&$modx,3861));
$modx->call('modResource', 'refreshURIs', array(&$modx,3866));
$modx->call('modResource', 'refreshURIs', array(&$modx,3387));
$modx->call('modResource', 'refreshURIs', array(&$modx,3389));
$modx->call('modResource', 'refreshURIs', array(&$modx,3598));
$modx->call('modResource', 'refreshURIs', array(&$modx,3843));
$modx->call('modResource', 'refreshURIs', array(&$modx,3844));
$modx->call('modResource', 'refreshURIs', array(&$modx,3845));
$modx->call('modResource', 'refreshURIs', array(&$modx,3481));
$modx->call('modResource', 'refreshURIs', array(&$modx,3554));
$modx->call('modResource', 'refreshURIs', array(&$modx,3615));
$modx->call('modResource', 'refreshURIs', array(&$modx,3617));
$modx->call('modResource', 'refreshURIs', array(&$modx,3620));
$modx->call('modResource', 'refreshURIs', array(&$modx,3895));
$modx->call('modResource', 'refreshURIs', array(&$modx,3896));
$modx->call('modResource', 'refreshURIs', array(&$modx,3897));
$modx->call('modResource', 'refreshURIs', array(&$modx,3730));
$modx->call('modResource', 'refreshURIs', array(&$modx,3740));
$modx->call('modResource', 'refreshURIs', array(&$modx,3741));

